export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const REMOVE_EXISTING_ERRORS = "REMOVE_EXISTING_ERRORS";

export const USER_REGISTRATION_START = "USER_REGISTRATION_START";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAIL = "USER_REGISTRATION_FAIL";

export const USER_LOGIN_START = "USER_LOGIN_START";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGED_OUT = "USER_LOGED_OUT";

export const LOAD_ITEMS_START = "LOAD_ITEMS_START";
export const LOAD_ITEMS_SUCCESS = "LOAD_ITEMS_SUCCESS";
export const LOAD_ITEMS_FAIL = "LOAD_ITEMS_FAIL";
export const REMOVE_STATUS = "REMOVE_STATUS";

export const REMOVE_ITEM_FROM_REDUX = "REMOVE_ITEM_FROM_REDUX";
